package generics.generic_methods.a_Set_utility;

public enum WaterColors {
    ZINC, LEMON_YELLOW, MEDIUM_YELLOW, DEEP_YELLOW, ORANGE, BRILEANT_RED, CRIMSON, MAGENTA, ROSE_MADDER, VIOLET, 
    CERULEN_BLUE_HUE, PHTHALO_BLUE, ULTRAMARINE, COBELT_BLUE_HUE, PERMENT_GREEN, VIRIDIAN_HUE, SAP_GREEN, YELLOW_OCHRE, 
    BURNT_SIENNA, RAW_AMBER, BURNT_UMBER, PAYNES_GRAY, IVORY_BLACK
}
